# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: "Check Roles"
  cisco.nac_dc_vxlan.common.check_roles:
    role_list: "{{ role_names }}"
  register: check_roles

# Check if golden and extended service model data files exist from previous runs
- name: Stat the Golden Service Model Data
  ansible.builtin.stat: path="{{ role_path }}/files/{{ MD.vxlan.global.name }}_service_model_golden.json"
  register: golden_stat

- name: Stat the Extended Service Model Data
  ansible.builtin.stat: path="{{ role_path }}/files/{{ MD.vxlan.global.name }}_service_model_extended.json"
  register: extended_stat

# Read and store previous golden service model data into a variable called 'smd_golden_previous'
- name: Read Previous Golden Service Model Data from Host
  ansible.builtin.include_vars:
    file: "{{ role_path }}/files/{{ MD.vxlan.global.name }}_service_model_golden.json"
  register: smd_golden_previous
  when: golden_stat.stat.exists and check_roles['save_previous']

# Rename golden file from previous run to append '_previous' to the filename
- name: Move Golden Service Model Data Previous
  ansible.builtin.command: mv "{{ role_path }}/files/{{ MD.vxlan.global.name }}_service_model_golden.json" "{{ role_path }}/files/{{ MD.vxlan.global.name }}_service_model_golden_previous.json"
  when: golden_stat.stat.exists and check_roles['save_previous']

# Rename extended file from previous run to append '_previous' to the filename
- name: Move Extended Service Model Data Previous
  ansible.builtin.command: mv "{{ role_path }}/files/{{ MD.vxlan.global.name }}_service_model_extended.json" "{{ role_path }}/files/{{ MD.vxlan.global.name }}_service_model_extended_previous.json"
  when: extended_stat.stat.exists and check_roles['save_previous']
