# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Check Roles
  cisco.nac_dc_vxlan.common.check_roles:
    role_list: "{{ role_names }}"
  register: check_roles
  delegate_to: localhost

- name: Read Run Map From Previous Run
  cisco.nac_dc_vxlan.common.read_run_map:
    model_data: "{{ MD_Extended }}"
  register: run_map_read_result
  delegate_to: localhost

- name: Debug Run Map Read Result
  ansible.builtin.debug:
    msg: "{{ run_map_read_result }}"
  delegate_to: localhost

- name: Initialize Run Map
  cisco.nac_dc_vxlan.common.run_map:
    model_data: "{{ MD_Extended }}"
    stage: starting_execution
  register: run_map
  delegate_to: localhost

- name: Manage Previous Service Model Data Files
  ansible.builtin.include_tasks: manage_model_files_previous.yml
  when: check_roles['save_previous']

- name: Manage Current Service Model Data Files
  ansible.builtin.include_tasks: manage_model_files_current.yml
  when: check_roles['save_previous']
