---

- name: Verify Connection to Switches on Port 22 Intended to be Managed by NDFC
  ansible.builtin.wait_for:
    host: >-
      {%- if item.management is defined and item.management -%}
      {%- if item.management.management_ipv4_address is defined and item.management.management_ipv4_address -%}
      {%- set _mgmt_ip = item.management.management_ipv4_address -%}
      {%- elif item.management.management_ipv6_address is defined and item.management.management_ipv6_address -%}
      {%- set _mgmt_ip = item.management.management_ipv6_address -%}
      {%- endif -%}
      {%- endif -%}
      {{ _mgmt_ip }}
    port: 22
    connect_timeout: 5
    delay: 0
    sleep: 5
    timeout: 30
    state: started
  ignore_errors: true
  register: switch_status
  delegate_to: localhost

- name: Add Switch to Connectivity Failed Switch Tracker
  ansible.builtin.set_fact:
    switch_tracker: >-
      {%- if item.management is defined and item.management -%}
      {%- if item.management.management_ipv4_address is defined and item.management.management_ipv4_address -%}
      {%- set _mgmt_ip = item.management.management_ipv4_address -%}
      {%- elif item.management.management_ipv6_address is defined and item.management.management_ipv6_address -%}
      {%- set _mgmt_ip = item.management.management_ipv6_address -%}
      {%- endif -%}
      {%- endif -%}
      {{ switch_tracker + [_mgmt_ip] }}
  when: switch_status["failed"] == true
  delegate_to: localhost
