# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---
defaults:
  vxlan:
    global:
      route_reflectors: 2
      anycast_gateway_mac: 20:20:00:00:00:aa
      auth_proto: MD5
      vpc:
        peer_link_vlan: 3600
        peer_keep_alive: management
        auto_recovery_time: 360
        delay_restore_time: 150
        peer_link_port_channel_id: 500
        advertise_pip: false
        advertise_pip_border_only: true
        domain_id_range: 1-1000
    topology:
      switches:
        routing_loopback_id: 0
        vtep_loopback_id: 1
        interfaces:
          topology_switch_access_interface:
            description: 'NetAsCode Access Interface'
            mtu: jumbo
            speed: auto
            enabled: true
            access_vlan: 1
            spanning_tree_portfast: true
            enable_bpdu_guard: true
          topology_switch_trunk_interface:
            description: 'NetAsCode Trunk Interface'
            mtu: jumbo
            speed: auto
            enabled: true
            trunk_allowed_vlans: none
            spanning_tree_portfast: true
            enable_bpdu_guard: true
          topology_switch_access_po_interface:
            description: 'NetAsCode Access PO Interface'
            mtu: jumbo
            speed: auto
            enabled: true
            access_vlan: 1
            pc_mode: active
            spanning_tree_portfast: true
            enable_bpdu_guard: true
          topology_switch_trunk_po_interface:
            description: 'NetAsCode Trunk PO Interface'
            mtu: jumbo 
            speed: auto
            enabled: true
            trunk_allowed_vlans: none
            pc_mode: active
            spanning_tree_portfast: true
            enable_bpdu_guard: true
          topology_switch_routed_interface:
            description: 'NetAsCode Routed Interface'
            mtu: 9216
            speed: auto
            enabled: true
          topology_switch_routed_sub_interface:
            description: 'NetAsCode Routed Sub Interface'
            mtu: 9216
            speed: auto
            enabled: true
          topology_switch_routed_po_interface:
            description: 'NetAsCode Routed PO Interface'
            mtu: 9216
            speed: auto
            enabled: true
            pc_mode: active
          topology_switch_loopback_interface:
            description: 'NetAsCode Loopback Interface'
            enabled: true
      vpc_peers:
        domain_id: 1
      fabric_links:
      edge_connections:
    underlay:
      general:
        routing_protocol: ospf
        enable_ipv6_underlay: false
        replication_mode: multicast
        fabric_interface_numbering: p2p
        subnet_mask: 30
        manual_underlay_allocation: false
        underlay_routing_loopback_id: 0
        underlay_vtep_loopback_id: 1
        underlay_routing_protocol_tag: UNDERLAY
        underlay_rp_loopback_id: 254
        intra_fabric_interface_mtu: 9216
        layer2_host_interfacde_mtu: 9216
        unshut_host_interfaces: true
      ipv4:
        underlay_routing_loopback_ip_range: 10.2.0.0/22
        underlay_vtep_loopback_ip_range: 10.3.0.0/22
        underlay_rp_loopback_ip_range: 10.254.254.0/24
        underlay_subnet_ip_range: 10.4.0.0/16
      ipv6:
        enable_ipv6_link_local_address: true
        underlay_subnet_mask: 126
      ospf:
        area_id: 0.0.0.0
        authentication_enable: false
        authentication_key_id: 127
      isis:
        level: level-2
        network_point_to_point: true
        authentication_enable: false
        authentication_key_id: 127
        overload_bit: true
        overload_bit_elapsed_time: 60
      bgp:
        authentication_enable: false
        authentication_key_type: 3
      multicast:
        group_subnet: 239.1.1.0/25
        rendezvous_points: 2
        rp_mode: asm
        underlay_rp_loopback_id: 254
        trm_enable: false
        trm_default_group: 239.1.1.0
        underlay_primary_rp_loopback_id: 2
        underlay_backup_rp_loopback_id: 3
        underlay_second_backup_rp_loopback_id: 4
        underlay_third_backup_rp_loopback_id: 5
      bfd:
        enable: false
        ibgp: false
        ospf: false
        pim: false
        isis: false
        authentication_enable: false
        authentication_key_id: 100
    overlay_services:
      vrfs:
        vrf_description: "Configured by Ansible NetAsCode"
        vrf_intf_desc: "Configured by Ansible NetAsCode"
        vrf_int_mtu: 9216
        loopback_route_tag: 12345
        max_bgp_paths: 1
        max_ibgp_paths: 2
        ipv6_linklocal_enable: true
        adv_host_routes: false
        adv_default_routes: true
        static_default_route: true
        disable_rt_auto: false
        netflow_enable: false
        no_rp: false
        redist_direct_routemap: FABRIC-RMAP-REDIST-SUBNET
        trm_enable: false
        trm_bgw_msite: false
      networks:
        net_description: "Configured by Ansible NetAsCode"
        is_l2_only: false
        arp_supress: false
        l3gw_on_border: false
        mtu_l3intf: 9216
        multicast_group_address: 239.1.1.1
        netflow_enable: false
        route_target_both: false
        route_tag: 12345
        trm_enable: false
      vrf_attach_groups:
        switches: []
      network_attach_groups:
        switches: []
    overlay_extension:
