---
namespace: cisco
name: nac_dc_vxlan
version: 0.1.0
readme: README.md
authors:
  - Devendra Gupta <devegupt>
  - Jesus Casero Diaz-Cano <JesusCaseroDiazCano>
  - Justin Burnette <juburnet>
  - Matt Tarkington <mtarking>
  - Mike Wiebe <mikewiebe>
  - Rafael Muller <rmuller>
  - Rameez Rahim <rrahimm>
  - Shangxin Du <shdu>
  - Udit Mehrotra <udmehrot>
  - Vladimir Joshevski <vjoshevs>
description: Ansible solution collection for VXLAN
license_file: LICENSE
tags: [cisco, ndfc, dcnm, nxos, networking, vxlan, evpn]
dependencies:
  "ansible.netcommon": ">=4.1.0"
  "cisco.nxos": ">=4.0.1"
  "cisco.dcnm": ">=2.4.0"
  "community.general": ">=8.5.0"
repository: https://github.com/netascode/ansible-dc-vxlan
