---
namespace: cisco
name: nac_dc_vxlan
version: 0.5.1-dev
readme: README.md
authors:
  - Devendra Gupta <devegupt>
  - Jesus Casero Diaz-Cano <JesusCaseroDiazCano>
  - Justin Burnette <juburnet>
  - Matt Tarkington <mtarking>
  - Mike Wiebe <mikewiebe>
  - Rafael Muller <rmuller>
  - Rameez Rahim <rrahimm>
  - Shangxin Du <shdu>
  - Udit Mehrotra <udmehrot>
  - Vladimir Joshevski <vjoshevs>
  - Slawomir Kaszlikowski <skaszlik>
  - Michal Kilar <mkilar>
  - Matt Thurston <mthurstocisco>
  - Peter Lewis <peter8498>
description: Ansible Solution Collection for VXLAN

repository: https://github.com/netascode/ansible-dc-vxlan
documentation: https://github.com/netascode/ansible-dc-vxlan/blob/main/README.md
homepage: https://netascode.cisco.com/docs/data_models/vxlan/overview/
issues: https://github.com/netascode/ansible-dc-vxlan/issues

license_file: LICENSE

tags: [cisco, dc, nd, ndfc, nxos, networking, vxlan, evpn, nac, sac]

dependencies:
  "ansible.netcommon": ">=4.1.0"
  "cisco.dcnm": ">=3.9.1"
  "community.general": ">=8.5.0"
