---
namespace: cisco
name: nac_dc_vxlan
version: 0.3.0
readme: README.md
authors:
  - Devendra Gupta <devegupt>
  - Jesus Casero Diaz-Cano <JesusCaseroDiazCano>
  - Justin Burnette <juburnet>
  - Matt Tarkington <mtarking>
  - Mike Wiebe <mikewiebe>
  - Rafael Muller <rmuller>
  - Rameez Rahim <rrahimm>
  - Shangxin Du <shdu>
  - Udit Mehrotra <udmehrot>
  - Vladimir Joshevski <vjoshevs>
description: Ansible Solution Collection for VXLAN

repository: https://github.com/netascode/ansible-dc-vxlan
documentation: https://github.com/cisco-open/ansible-collection-catalystwan/blob/main/README.md
homepage: https://netascode.cisco.com/data_model/vxlan/overview
issues: https://github.com/netascode/ansible-dc-vxlan/issues

license_file: LICENSE

tags: [cisco, ndfc, dcnm, nxos, networking, vxlan, evpn, nac, sac]

dependencies:
  "ansible.netcommon": ">=4.1.0"
  "cisco.nxos": ">=4.0.1"
  "cisco.dcnm": ">=3.6.0"
  "community.general": ">=8.5.0"
