# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Initialize changes_detected Var
  ansible.builtin.set_fact:
    changes_detected_vpc_domain: false
  delegate_to: localhost

- name: Set file_name Var
  ansible.builtin.set_fact:
    file_name: "ndfc_vpc_domain.yml"
  delegate_to: localhost

- name: Stat Previous File If It Exists
  ansible.builtin.stat:
    path: "{{ path_name }}{{ file_name }}"
  register: data_file_previous
  delegate_to: localhost

- name: Backup Previous Data File If It Exists
  ansible.builtin.copy:
    src: "{{ path_name }}{{ file_name }}"
    dest: "{{ path_name }}{{ file_name }}.old"
  when: data_file_previous.stat.exists

- name: Delete Previous Data File If It Exists
  ansible.builtin.file:
    state: absent
    path: "{{ path_name }}{{ file_name }}"
  delegate_to: localhost
  when: data_file_previous.stat.exists

- name: Build vPC Domain
  ansible.builtin.template:
    src: ndfc_vpc/ndfc_vpc_domain.j2
    dest: "{{ path_name }}{{ file_name }}"
  delegate_to: localhost

- name: Set vpc_domain Var default
  ansible.builtin.set_fact:
    vpc_domain: []
  delegate_to: localhost

- name: Set vpc_domain Var
  ansible.builtin.set_fact:
    vpc_domain: "{{ lookup('file', path_name + file_name) | from_yaml }}"
  when: MD_Extended.vxlan.topology.vpc_peers | length > 0
  delegate_to: localhost

- name: GET VPC DOMAIN ID
  cisco.dcnm.dcnm_resource_manager:
    fabric: "{{ vxlan.fabric.name }}"
    state: query
    config:
      - pool_name: VPC_DOMAIN_ID
  register: existing_vpc_domain_id

- name: Check VPC DOMAIN
  cisco.nac_dc_vxlan.dtc.vpc_domain_check:
    data_source_vpc_domain: "{{ vpc_domain }}"
    remote_vpc_domain: "{{ existing_vpc_domain_id.response }}"
  delegate_to: localhost

- name: Diff Previous and Current Data Files
  cisco.nac_dc_vxlan.dtc.diff_model_changes:
    file_name_previous: "{{ path_name }}{{ file_name }}.old"
    file_name_current: "{{ path_name }}{{ file_name }}"
  register: file_diff_result
  delegate_to: localhost

- name: Set File Change Flag Based on File Diff Result
  ansible.builtin.set_fact:
    changes_detected_vpc_domain: true
  delegate_to: localhost
  when:
    - file_diff_result.file_data_changed
    - check_roles['save_previous']