---

name: Documentation Report
description: Report a documentation issue for the VXLAN as Code collection
title: Documentation Report Title
labels:
  - documentation
  - doc
body:
  - type: markdown
    attributes:
      value: |
        Thanks for creating a documentation issue to help us improve the VXLAN as Code collection. 
        Please fill out the sections below to help us understand and reproduce the issue you are facing.

  - type: markdown
    attributes:
      value: |
        ### Community Note
        Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
        If you are interested in working on this issue or have submitted a pull request, please leave a comment

  - type: dropdown
    id: role
    attributes:
      label: Which role is the documentation update related?
      multiple: false
      options:
        - cisco.nac_dc_vxlan.validate
        - cisco.nac_dc_vxlan.dtc.create
        - cisco.nac_dc_vxlan.dtc.deploy
        - cisco.nac_dc_vxlan.dtc.remove
        - other
    validations:
      required: true

  - type: dropdown
    id: data-model
    attributes:
      label: Which section of the data model is the documentation update related?
      multiple: false
      options:
        - vxlan.global
        - vxlan.topology
        - vxlan.underlay
        - vxlan.overlay_services
        - vxlan.overlay_extensions
        - vxlan.policy
        - defaults.vxlan
        - other
    validations:
      required: true

  - type: textarea
    id: new-or-affected-documentation
    attributes:
      label: New or Affected Documentation
      description: Please list the new or affected documentation sections
      placeholder: Documentation section or new documentation that needs attention
      render: shell
    validations:
      required: true

  - type: textarea
    id: documentation-description
    attributes:
      label: Documentation Description
      description: Please leave a helpful description of the documentation report here
      placeholder: Documentation section or new documentation that needs attention
      render: shell
    validations:
      required: true

  - type: textarea
    id: ansible-version
    attributes:
      label: Ansible Version
      description: Please provide your Ansible version used when encountering this issue
      placeholder: ansible --version
      render: shell
    validations:
      required: false

  - type: textarea
    id: ansible-collection-versions
    attributes:
      label: Ansible Collection Versions
      description: Please provide your Ansible Collection versions used when encountering this issue
      placeholder: ansible-galaxy collection list
      render: shell
    validations:
      required: false
    
  - type: textarea
    id: ndfc-version
    attributes:
      label: Cisco NDFC Version
      description: Please provide your Cisco NDFC version used when encountering this issue
      render: shell
    validations:
      required: false

  - type: textarea
    id: nxos-version
    attributes:
      label: Cisco NX-OS Version
      description: Please provide your Cisco NX-OS version used when encountering this issue
      render: shell
    validations:
      required: false
