# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Manage Fabric Entry Point
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+     Manage Fabric {{ data_model_extended.vxlan.fabric.name }}"
      - "----------------------------------------------------------------"

- name: Check Fabric Exists in Nexus Dashboard
  cisco.dcnm.dcnm_rest:
    method: GET
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ data_model_extended.vxlan.fabric.name }}"
  register: get_result
  failed_when: false

- name: Manage Fabric in Nexus Dashboard (Custom)
  when:
    - get_result.response.DATA is defined
    - get_result.response.DATA
    - get_result.response.DATA.fabricTechnologyFriendly == "Custom"
    - get_result.response.DATA.templateFabricType == "Custom Network"
  block:
    # The dcnm_rest module is used for legacy support where the Exteranl fabric type was of type Custom.
    # This will continue to allow for the fabric to be updated in place without having to remove and re-add the fabric which would be disruptive.
    # The format of the fabric_config normalized with all other fabrics, meaning the generated data is a list of fabrics.
    # For this legacy scenario using the dcnm_rest module requires two operatons to maintain backwards compatibility:
    # 1) The fabric config needs to reference the first item in the list of fabrics
    # 2) The DEPLOY key needs to be removed from the fabric_config as it is used by the dcnm_fabric module but is not expected by the REST API
    # Using Ansible builtin filters; dict2items, rejectattr, list, items2dict, and to_json, the data can be transformed inline:
    # * dict2items - transforms the fabric_config dict into a list of key/value pairs
    # * rejectattr - removes the item with the key of DEPLOY
    # * list - ensures the data is in a list format
    # * items2dict - transforms the data back into a dict format for use in the REST API call
    # * to_json - converts the data to JSON format for the REST API call
    - name: Manage Fabric in Nexus Dashboard (PUT)
      cisco.dcnm.dcnm_rest:
        method: PUT
        path: '/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ data_model_extended.vxlan.fabric.name }}/External_Fabric'
        json_data: "{{ vars_common_external.fabric_config[0] | dict2items | rejectattr('key', 'equalto', 'DEPLOY') | list | items2dict | to_json }}"

- name: Manage Fabric in Nexus Dashboard
  cisco.dcnm.dcnm_fabric:
    state: merged
    config: "{{ vars_common_external.fabric_config }}"
    skip_validation: true
  when: >
    (get_result.response.DATA is not defined) or
    (get_result.response.DATA is defined and not get_result.get('response', false) and not get_result.get('response').get('DATA')) or
    (get_result.response.DATA.fabricTechnologyFriendly != "Custom") or
    (get_result.response.DATA.templateFabricType != "Custom Network")
