---

- name: Delete content & directory
  ansible.builtin.file:
    state: absent
    path: "{{ path_name }}"
  delegate_to: localhost

- name: Recreate the directory
  ansible.builtin.file:
    path: "{{ path_name }}"
    state: directory
    mode: '0755'
  delegate_to: localhost