---

- name: Set inv_file_name Var
  ansible.builtin.set_fact:
    inv_file_name: "{{ MD.fabric.global.name }}_inventory.yml"

- name: Set Path For Inventory File Lookup
  ansible.builtin.set_fact:
    inv_file_path: "{{ role_path }}/files/{{ inv_file_name }}"

- name: Build Fabric Switch Inventory List From Template
  ansible.builtin.template:
    src: ndfc_inventory.j2
    dest: "{{ inv_file_path }}"

- name: Create Empty inv_config Var
  ansible.builtin.set_fact:
    inv_config: []

- name: Set inv_config Var
  ansible.builtin.set_fact:
    inv_config: "{{ lookup('file', inv_file_name) | from_yaml }}"
  when: (MD_Extended.fabric.topology.switches | default([])) | length > 0
