---

- name: Set vpc_peering_file_name Var
  ansible.builtin.set_fact:
    vpc_peering_file_name: "{{ MD.vxlan.global.name }}_ndfc_vpc_peering.yml"

- name: Build vPC Peering
  ansible.builtin.template:
    src: ndfc_vpc_peering.j2
    dest: "{{ role_path }}/files/{{ vpc_peering_file_name }}"

- name: Set vpc_peering Var default
  ansible.builtin.set_fact:
    vpc_peering: []

- name: Set vpc_peering Var
  ansible.builtin.set_fact:
    vpc_peering: "{{ lookup('file', vpc_peering_file_name) | from_yaml }}"
  when: MD_Extended.vxlan.topology.vpc_peers | length > 0
