---
- name: Set interface_all_file_name Var
  ansible.builtin.set_fact:
    ndfc_interface_all_file_name: "{{ MD.fabric.global.name }}_ndfc_interface_all.yml"

- name: Set interface_all Var
  ansible.builtin.set_fact:
    interface_all: []

- name: Set interface_all Var
  ansible.builtin.set_fact:
    interface_all: "{{ interface_access + interface_access_po + interface_trunk + interface_trunk_po + interface_routed + interface_po_routed + sub_interface_routed + interface_vpc + int_loopback_config }}"
  when: MD_Extended.fabric.topology.interfaces.modes.all.count >0

- name: Save interface_all
  ansible.builtin.copy:
    content: "{{ interface_all | to_nice_yaml }}"
    dest: "{{ role_path }}/files/{{ ndfc_interface_all_file_name }}"

