# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Initialize changes_detected Var
  ansible.builtin.set_fact:
    changes_detected_inventory: false
  delegate_to: localhost

- name: Set file_name Var
  ansible.builtin.set_fact:
    file_name: "{{ MD.vxlan.global.name }}_ndfc_inventory.yml"
  delegate_to: localhost

- name: Stat Previous File If It Exists
  ansible.builtin.stat:
    path: "{{ role_path }}/files/{{ file_name }}"
  register: data_file_previous
  delegate_to: localhost

- name: Backup Previous Data File If It Exists
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ file_name }}"
    dest: "{{ role_path }}/files/{{ file_name }}.old"
  when: data_file_previous.stat.exists

- name: Delete Previous Data File If It Exists
  ansible.builtin.file:
    state: absent
    path: "{{ role_path }}/files/{{ file_name }}"
  delegate_to: localhost
  when: data_file_previous.stat.exists

- name: Set Path For Inventory File Lookup
  ansible.builtin.set_fact:
    inv_file_path: "{{ role_path }}/files/{{ file_name }}"
  delegate_to: localhost

- name: Build Fabric Switch Inventory List From Template
  ansible.builtin.template:
    src: ndfc_inventory.j2
    dest: "{{ inv_file_path }}"
  delegate_to: localhost

- name: Create Empty inv_config Var
  ansible.builtin.set_fact:
    inv_config: []
  delegate_to: localhost

- name: Set inv_config Var
  ansible.builtin.set_fact:
    inv_config: "{{ lookup('file', file_name) | from_yaml }}"
  when: (MD_Extended.vxlan.topology.switches | default([])) | length > 0
  delegate_to: localhost

- name: Retrieve NDFC Device Username and Password from Group Vars and update inv_config
  cisco.nac_dc_vxlan.common.get_credentials:
    inv_list: "{{ inv_config }}"
  register: updated_inv_config
  no_log: true

- name: Credential Retrieval Failed
  ansible.builtin.fail:
    msg: "{{ updated_inv_config }}"
  when: updated_inv_config['retrieve_failed']
  delegate_to: localhost

- name: Diff Previous and Current Data Files
  cisco.nac_dc_vxlan.dtc.diff_model_changes:
    file_name_previous: "{{ role_path }}/files/{{ file_name }}.old"
    file_name_current: "{{ role_path }}/files/{{ file_name }}"
  register: file_diff_result
  delegate_to: localhost

- name: Set File Change Flag Based on File Diff Result
  ansible.builtin.set_fact:
    changes_detected_inventory: true
  delegate_to: localhost
  when:
    - file_diff_result.file_data_changed
    - check_roles['save_previous']