# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Set inv_file_name Var
  ansible.builtin.set_fact:
    inv_file_name: "{{ MD.vxlan.global.name }}_ndfc_inventory.yml"

- name: Set Path For Inventory File Lookup
  ansible.builtin.set_fact:
    inv_file_path: "{{ role_path }}/files/{{ inv_file_name }}"

- name: Build Fabric Switch Inventory List From Template
  ansible.builtin.template:
    src: ndfc_inventory.j2
    dest: "{{ inv_file_path }}"

- name: Create Empty inv_config Var
  ansible.builtin.set_fact:
    inv_config: []

- name: Set inv_config Var
  ansible.builtin.set_fact:
    inv_config: "{{ lookup('file', inv_file_name) | from_yaml }}"
  when: (MD_Extended.vxlan.topology.switches | default([])) | length > 0

- name: Retrieve NDFC Device Username and Password from Group Vars and update inv_config
  cisco.nac_dc_vxlan.common.get_credentials:
    inv_list: "{{ inv_config }}"
  register: updated_inv_config
  no_log: true
