---

- name: Set interface_trunk_po_file_name Var
  ansible.builtin.set_fact:
    interface_trunk_po_file_name: "{{ MD.vxlan.global.name }}_ndfc_interface_trunk_po.yml"

- name: Build Interface
  ansible.builtin.template:
    src: ndfc_interface_trunk_po.j2
    dest: "{{ role_path }}/files/{{ interface_trunk_po_file_name }}"

- name: Set interface_trunk_po Var
  ansible.builtin.set_fact:
    interface_trunk_po: []

- name: Set interface_trunk_po Var
  ansible.builtin.set_fact:
    interface_trunk_po: "{{ lookup('file', interface_trunk_po_file_name) | from_yaml }}"
  when: MD_Extended.vxlan.topology.interfaces.modes.trunk_po.count >0
