# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Set link_vpc_peering_file_name Var
  ansible.builtin.set_fact:
    link_vpc_peering_file_name: "{{ MD.vxlan.global.name }}_ndfc_link_vpc_peering_.yml"
  delegate_to: localhost

- name: Build Links for VPC Peering
  ansible.builtin.template:
    src: ndfc_links_vpc_peering.j2
    dest: "{{ role_path }}/files/{{ link_vpc_peering_file_name }}"
  delegate_to: localhost

- name: Set link_vpc_peering Var default
  ansible.builtin.set_fact:
    link_vpc_peering: []
  delegate_to: localhost

- name: Set link_vpc_peering Var
  ansible.builtin.set_fact:
    link_vpc_peering: "{{ lookup('file', link_vpc_peering_file_name) | from_yaml }}"
  when: MD_Extended.vxlan.topology.vpc_peers | length > 0
  delegate_to: localhost
