# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT
---

- block:
  - ansible.builtin.debug: msg="Removing Unmanaged Edge Connections From Switches. This could take several minutes..."

  - name: Build Unmanaged Edge Connection Payload
    cisco.nac_dc_vxlan.dtc.unmanaged_edge_connections:
      switch_data: "{{ switch_list.response.DATA }}"
      edge_connections: "{{ edge_connections }}"
    register: unmanaged_edge_connections_config
    # do not delegate_to: localhost as this action plugin uses Python to execute cisco.dcnm.dcnm_rest

  - name: Remove Unmanaged NDFC Edge Connections
    cisco.dcnm.dcnm_policy:
      fabric: "{{ MD_Extended.vxlan.global.name  }}"
      use_desc_as_key: true
      config: "{{ unmanaged_edge_connections_config.unmanaged_edge_connections }}"
      deploy: false
      state: deleted
    when: unmanaged_edge_connections_config.unmanaged_edge_connections | length > 0
    vars:
        ansible_command_timeout: 3000
        ansible_connect_timeout: 3000
  when:
    - switch_list.response.DATA | length > 0
    - (edge_connections_delete_mode is defined) and (edge_connections_delete_mode is true|bool)

- ansible.builtin.debug:
    msg:
      - "--------------------------------------------------------------------------------------------------------"
      - "+ SKIPPING Remove Unmanaged Edge Connections from Switches task because edge_connections_delete_mode flag is set to False   +"
      - "--------------------------------------------------------------------------------------------------------"
  when: not ((edge_connections_delete_mode is defined) and (edge_connections_delete_mode is true|bool))
