# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

# This is just a placeholder example and is not currently enabled as part of
# the solution workflow.  The module calls below represent a pre-provision
# workflow and how the dcnm_inventory module can be used to pre-provision
# a switch.

  tasks:
    - name: Pre-provision switch Configuration
      cisco.dcnm.dcnm_inventory:
        fabric: nac-ndfc1
        state: merged # Only 2 options supported merged/query for poap config
        config:
        # All the values below are mandatory if poap configuration is being done - state is merged
        - seed_ip: 192.168.9.14
          user_name: admin
          password: cisco.123
          role: border
          poap:
            - preprovision_serial: 9Y0K4YPFFFF
              model: N9K-C9300v
              version: 9.3(7)
              hostname: netascode-leaf3
              # image_policy: "prepro_image_policy"
              config_data:
                modulesModel: [N9K-X9364v, N9K-vSUP]
                gateway: 192.168.9.1/24
      vars:
        ansible_command_timeout: 1000
        ansible_connect_timeout: 1000

    # Note: Calling the module in this way will switch out the fake
    # serial number with the actual switch serial number and also
    # poap the switch if it's in poap mode and appears in the NDFC
    # poap list.
    - name: Pre-provision switch Configuration
      cisco.dcnm.dcnm_inventory:
        fabric: nac-ndfc1
        state: merged # Only 2 options supported merged/query for poap config
        config:
        # All the values below are mandatory if poap configuration is being done - state is merged
        - seed_ip: 192.168.9.14
          user_name: admin
          password: cisco.123
          role: border
          poap:
            - preprovision_serial: 9Y0K4YPFFFF
              serial_number: 9Y0K4YPFV64
      vars:
        ansible_command_timeout: 1000
        ansible_connect_timeout: 1000

          # preprovision:
          #   serial: 9Y0K4YPFFFF
          #   model: N9K-C9300v
          #   version: 9.4(8)
          #   modulesModel: [N9K-X9364v, N9K-vSUP]
          #   gateway: 10.15.9.1/24 # Add netmask to management key
