---

# --------------------------------------------------------------------
# Manage Intra Fabric Links Configuration on NDFC (prepare links for vpc peering)
# --------------------------------------------------------------------

- name: Manage Intra Fabric Links for vpc peering
  cisco.dcnm.dcnm_links:
    state: replaced
    src_fabric: "{{ MD_Extended.vxlan.global.name }}"
    config: "{{ link_vpc_peering }}"
  vars:
      ansible_command_timeout: 3000
      ansible_connect_timeout: 3000

# --------------------------------------------------------------------
# Manage vPC Peering
# --------------------------------------------------------------------

- name: Manage vPC Peering
  cisco.dcnm.dcnm_vpc_pair:
    src_fabric: "{{ MD.vxlan.global.name }}"
    deploy: false
    state: replaced
    config: "{{ vpc_peering }}"
