# Copyright (c) 2024 Cisco Systems, Inc. and its affiliates
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

---

- name: Add NDFC Fabric Devices {{ MD.vxlan.global.name }}
  cisco.dcnm.dcnm_inventory:
    fabric: "{{ MD.vxlan.global.name }}"
    config: "{{ updated_inv_config['updated_inv_list'] }}"
    deploy: false
    save: true
    state: merged
  vars:
    ansible_command_timeout: 3000
    ansible_connect_timeout: 3000
  when: MD_Extended.vxlan.topology.switches | length > 0

- name: Create List of Switch Serial Numbers from Data Model
  ansible.builtin.set_fact:
    md_serial_numbers: "{{ MD_Extended.vxlan.topology.switches | map(attribute='serial_number') | list }}"
  delegate_to: localhost

- name: Build Switch Hostname Policy Payload from Data Model Update
  cisco.nac_dc_vxlan.dtc.update_switch_hostname_policy:
    model_data: "{{ MD_Extended }}"
    switch_serial_numbers: "{{ md_serial_numbers }}"
    template_name: host_11_1
  register: results
# do not delegate_to: localhost as this action plugin uses Python to execute cisco.dcnm.dcnm_rest

- name: Join List of Switch Hostname Policy IDs from NDFC
  ansible.builtin.set_fact:
    policy_ids: "{{ results.policy_update.values() | map(attribute='policyId') | list | join('%2C') }}"
  when: results.policy_update | length > 0
  delegate_to: localhost

- name: Update Switch Hostname Policy in NDFC
  cisco.dcnm.dcnm_rest:
    method: PUT
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/policies/{{ policy_ids }}/bulk"
    json_data: "{{ results.policy_update.values() | list | to_json }}"
  when: results.policy_update | length > 0
