---

- debug: msg="Building NDFC MSD Child Fabric Data"

# Notes on items that still need support for MSD
#
# - Fabric Settings for MSD (Need Customer Requirements Here)
# - Fabric Settings for ISN (Need Customer Requirements Here)
# - Enable Interface Management under ISN workflow
# - Enable Policy Management under ISN/MSD worflows
# - Verify addition of multiple ISN Fabrics/Devies
#    (Test Two ISN Fabrics with two ISN devices - Full Mesh)
#    (Configure interfaces between the ISN devices)
#    (What policy should be applied between the ISN devices)
# - Verify support of VRF / Network properties at MSD level
# - Enable support of VRF / Netowrk properties at Child level under MSD fabric
# - Verify Order of Operations
#    - Create VXLAN / ISN Fabrics then MSD Fabric + Association
#    - Create MSD Fabric then VXLAN / ISN Fabrics + Association
#    - VRF / Network problem when child fabrics moved under MSD but MSD level VRF/Net model data is empty
#      (Result is all VRF/Networks are removed after they get moved under MSD - can be controlled with flag)